import React, { useState } from "react";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  StatusBar,
  TouchableOpacity,
} from "react-native";
import Animated, {
  FadeIn,
  FadeOut,
  LinearTransition,
} from "react-native-reanimated";
import { ChevronDown, ChevronUp } from "lucide-react-native";
import { scaleFont } from "../../utils/responsive";
import { appColors } from "../../themes/appColors";

const accordionData = [
  {
    title: "Terms of Service",
    content: `ELUNARA – TERMS OF SERVICE
Last Updated: 31 March, 2026

These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "you", or "your") and Elunara ("Elunara", "we", "us", or "our"), governing your access to and use of Elunara's website, mobile application, APIs, software, content, and related services (collectively, the "Platform"). Elunara is an AI-powered educational platform designed to deliver personalized, ethical, and multilingual learning experiences for management education.

By accessing, registering on, or using the Platform, you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, you must immediately discontinue use of the Platform.

1. DEFINITIONS
"Account" means a registered user profile on the Platform.
"AI Outputs" means responses, recommendations, explanations, or content generated by artificial intelligence systems.
"Content" means all text, graphics, data, software, audio, video, assessments, and educational materials available on the Platform.
"User Content" means any data, prompts, text, files, or materials submitted by users.
"Third-Party Services" means services, tools, or platforms not owned or controlled by Elunara.

2. ELIGIBILITY & LEGAL CAPACITY
2.1 Users must be at least 13 years of age. Users below 18 years may use the Platform only with verifiable parental or legal guardian consent.

2.2 By using the Platform, you represent that you have the legal capacity to enter into a binding contract under Indian law.

2.3 Elunara reserves the right to refuse access, suspend, or terminate accounts that do not meet eligibility requirements.

3. ACCOUNT REGISTRATION & SECURITY
3.1 Users must provide accurate, current, and complete information at registration.

3.2 Users are solely responsible for maintaining the confidentiality of login credentials and for all activities under their Account.

3.3 You agree to notify Elunara immediately of any unauthorized use or security breach.

4. NATURE OF SERVICES & AI LIMITATIONS
4.1 Elunara provides AI-assisted educational tools, explanations, adaptive learning pathways, and academic support.

4.2 The Platform is a learning aid only and does not provide professional, legal, financial, medical, or certification advice.

4.3 AI Outputs are probabilistic, automated, and may be inaccurate or incomplete. Users must independently verify AI Outputs before relying on them.

4.4 Elunara does not guarantee learning outcomes, grades, certifications, or employment results.

5. ACCEPTABLE USE POLICY
Users shall not:

Engage in cheating, plagiarism, impersonation, or academic misconduct;
Represent AI Outputs as certified, professional, or expert advice;
Use the Platform for unlawful, deceptive, abusive, or unethical purposes;
Reverse engineer, scrape, bypass safeguards, or disrupt the Platform;
Use the Platform to develop or train competing AI models or services;
Upload content infringing intellectual property or privacy rights.

Violation may result in suspension, termination, and legal action.

6. USER CONTENT & LICENSE
6.1 Users retain ownership of User Content.

6.2 By submitting User Content, users grant Elunara a worldwide, non-exclusive, royalty-free, sublicensable license to host, store, process, analyze, reproduce, and display such content solely for providing, maintaining, securing, and improving the Platform.

6.3 Users represent and warrant that they have all rights necessary to submit User Content.

7. AI TRAINING & PLATFORM IMPROVEMENT
7.1 Elunara may use anonymized, aggregated, or de-identified data to improve, test, and enhance AI systems.

7.2 Personal data is not used to train AI models in a manner that identifies individual users unless permitted by law or explicit consent is obtained.

8. INTELLECTUAL PROPERTY RIGHTS
8.1 All intellectual property rights in the Platform, including software, algorithms, AI models, trademarks, and branding, are owned by Elunara or its licensors.

8.2 Except as expressly permitted, no rights are granted to users.

9. SUBSCRIPTIONS, FEES & PAYMENTS
9.1 Certain features require paid subscriptions.

9.2 Pricing, billing cycles, and features will be disclosed prior to purchase.

9.3 Fees are non-refundable except as required under Indian consumer protection laws.

9.4 Elunara may revise pricing or features with prior notice.

10. THIRD-PARTY SERVICES
10.1 The Platform may integrate or link to Third-Party Services.

10.2 Elunara is not responsible for third-party content, services, or practices.

11. SUSPENSION & TERMINATION
11.1 Elunara may suspend or terminate access without notice for:

Breach of these Terms;
Legal or regulatory compliance;
Security or integrity risks.

11.2 Upon termination, user access rights cease immediately.

12. DISCLAIMER OF WARRANTIES
The Platform is provided on an "as is" and "as available" basis. Elunara disclaims all warranties, express or implied, including accuracy, reliability, fitness for a particular purpose, and uninterrupted availability.

13. LIMITATION OF LIABILITY
To the maximum extent permitted by law:

Elunara shall not be liable for indirect, incidental, or consequential damages;
Aggregate liability shall not exceed fees paid by the user in the preceding six (6) months.

14. INDEMNIFICATION
Users agree to indemnify and hold harmless Elunara from claims, damages, losses, and expenses arising from:

User Content;
Breach of these Terms;
Misuse of the Platform.

15. ARBITRATION & DISPUTE RESOLUTION
15.1 Any dispute shall be resolved through arbitration under the Arbitration and Conciliation Act, 1996.

15.2 Seat and venue of arbitration shall be Kolkata, India.

15.3 Arbitration proceedings shall be conducted in English.

16. GOVERNING LAW & JURISDICTION
These Terms are governed by the laws of India. Subject to arbitration, courts at Kolkata shall have exclusive jurisdiction.

17. SEVERABILITY
If any provision is held unenforceable, remaining provisions shall remain valid.

18. FORCE MAJEURE
Elunara shall not be liable for failure or delay due to events beyond reasonable control, including natural disasters, government actions, or technical failures.

19. NOTICES & CONTACT
Legal notices or queries may be sent to:

Email: security@elunara.ai

Last Updated: 31 March, 2026`,
  },
  {
    title: "Community Guidelines",
    content: `COMMUNITY GUIDELINE
Last Updated: March 31, 2026

1. Purpose and Scope
Elunara is a learning support and educational technology platform designed to foster constructive, inclusive, and respectful interactions among users, educators, mentors, and administrators. These Community Guidelines set out the standards of behavior expected from all users while accessing or using Elunara's website, mobile application, discussion spaces, learning forums, and related services.

By using the Platform, you agree to comply with these Guidelines in addition to Elunara's Terms of Service, Privacy Policy, and other applicable policies.

2. Respectful Conduct
All users are expected to engage with others in a respectful, professional, and lawful manner.

Users must:

Communicate politely and constructively
Respect differing opinions, backgrounds, and viewpoints
Engage in discussions in good faith
Refrain from personal attacks or hostile conduct
Treat educators, moderators, and platform staff with courtesy

Elunara aims to maintain a safe learning environment free from intimidation, hostility, or abuse.

3. Prohibited Behaviour
The following conduct is strictly prohibited on the Platform:

3.1. Harassment and Bullying
Threats, intimidation, or abusive language
Repeated unwanted contact or targeting of individuals
Doxxing or sharing personal information without consent

3.2. Hate Speech and Discrimination
Content that promotes hatred, violence, or discrimination based on protected characteristics
Derogatory or inflammatory remarks targeting individuals or groups
Content that violates applicable anti-discrimination laws

3.3. Misinformation and Deceptive Practices
Deliberate dissemination of false or misleading information
Impersonation of another person or entity
Misrepresentation of qualifications, credentials, or authority

3.4. Illegal and Harmful Content
Content that violates any applicable law or regulation
Promotion of violence, self-harm, or unlawful activities
Obscene, sexually explicit, or exploitative content
Content involving minors that violates child protection laws

3.5. Platform Abuse
Attempting to manipulate platform features or algorithms
Spamming, flooding discussions, or posting irrelevant promotional content
Circumventing safeguards, moderation systems, or access controls

4. User Responsibilities
Users are responsible for:

All content they create, upload, or share on the Platform
Ensuring that their conduct complies with these Guidelines and applicable laws
Reporting violations or abusive behavior through designated reporting channels
Maintaining the confidentiality and security of their account credentials

Elunara does not endorse user-generated content and reserves the right to remove content that violates these Guidelines.

5. Reporting Violations
Users may report violations of these Community Guidelines by:

Using in-platform reporting tools, or
Contacting Elunara's Grievance Officer through the contact details provided on the website

Reports should include sufficient details to allow for review and investigation. Elunara will make reasonable efforts to address complaints promptly and fairly.

6. Enforcement and Disciplinary Action
Elunara reserves the right to take appropriate action in response to violations, including but not limited to:

Content removal or restriction
Temporary suspension of user privileges
Permanent account termination
Reporting to law enforcement or regulatory authorities where required

Disciplinary action may be taken without prior notice in cases involving serious misconduct or legal risk.

7. Legal Compliance (India)
These Community Guidelines are framed in compliance with applicable Indian laws, including but not limited to:

Information Technology Act, 2000 and related Rules
Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021
Digital Personal Data Protection Act, 2023
Bharatiya Nyaya Sanhita, 2023 (where applicable to offences such as harassment, intimidation, or hate speech)
Other applicable central or state laws and regulations

Users are solely responsible for ensuring that their conduct does not violate any applicable law.

8. Moderation and Content Review
Elunara uses a combination of automated systems and human moderation to enforce these Guidelines. While Elunara strives to ensure fair and consistent enforcement, it does not guarantee that all prohibited content will be immediately identified or removed.

9. Amendments and Updates
Elunara may update these Community Guidelines from time to time to reflect changes in law, platform functionality, or community needs. Continued use of the Platform after updates constitutes acceptance of the revised Guidelines.

10. Contact Information
For questions, concerns, or reports related to these Community Guidelines, please contact:

Grievance Officer: [Name / Designation]
Email: security@elunara.ai
Address: [Registered Office Address]`,
  },
  {
    title: "Content Moderation Policy",
    content: `CONTENT MODERATION POLICY
Last Updated: March 31, 2026

1. Purpose of This Policy
This Content Moderation Policy explains how Elunara monitors, reviews, and manages content shared, generated, uploaded, or otherwise made available on its platform. The policy is designed to ensure a safe, lawful, respectful, and educational environment for all users, while complying with applicable laws in India.

This policy forms an integral part of Elunara's Terms of Service and is binding on all users of the platform.

2. Scope and Applicability
This policy applies to all forms of content on the Elunara platform, including but not limited to:

Text, images, audio, video, and files uploaded by users
Prompts, queries, and inputs submitted to AI tools
AI-generated outputs shared, stored, or published by users
Comments, feedback, messages, or community interactions (if applicable)

3. Moderation Rights
Elunara reserves the right, but not the obligation, to monitor, review, screen, restrict, edit, block, disable or remove any content at its sole discretion if such content:

Violates applicable laws or regulations
Breaches Elunara's Terms of Service or platform policies
Poses legal, reputational, ethical, or security risks
Harms users, third parties, or the integrity of the platform

Elunara may take such action with or without prior notice, depending on the nature and severity of the violation.

4. Restricted and Prohibited Content
Users are strictly prohibited from creating, uploading, sharing, or distributing content that includes or relates to the following:

4.1. Illegal or Unlawful Content
Content that violates any applicable law in India or elsewhere
Content promoting or facilitating criminal activities
Content related to terrorism, extremism, or unlawful organizations

4.2. Hate Speech, Harassment, and Abuse
Content that promotes hatred or violence against individuals or groups based on race, caste, religion, gender, sexual orientation, disability, or nationality
Threats, bullying, harassment, or intimidation
Dehumanizing or abusive language

4.3. Obscene, Sexual, or Harmful Content
Obscene, pornographic, or sexually explicit material
Content exploiting or endangering children or minors
Content promoting self-harm, suicide, or extreme violence

4.4. Defamatory or Misleading Content
False statements presented as facts that harm the reputation of individuals or organizations
Impersonation of any person, authority, or institution
Deliberate misinformation or disinformation

4.5. Intellectual Property Violations
Content that infringes copyrights, trademarks, patents, or trade secrets
Unauthorized reproduction or distribution of proprietary materials
Plagiarized or pirated content

4.6. Other Prohibited Content
Content containing malware, viruses, or harmful code
Spam, scams, or fraudulent schemes
Content that circumvents platform safeguards or security features

5. User Responsibilities
Users are solely responsible for the content they submit, generate, or share using Elunara. Users agree to:

Ensure their content complies with all applicable laws and policies
Use AI-generated content responsibly and ethically
Not rely on Elunara to validate the legality or accuracy of content
Promptly remove or correct content if notified of a violation

6. Automated and Human Moderation
Elunara may use a combination of automated systems and human review to detect, flag, and assess potentially violating content. Automated moderation tools are used to enhance safety and scale, but final decisions may involve human judgment.

Elunara does not guarantee that all prohibited content will be detected or removed immediately.

7. Reporting of Content
Users may report content they believe violates this policy by contacting Elunara through the grievance or reporting mechanism provided on the platform.

Reports should include sufficient details to allow proper review. Frivolous or abusive reports may result in action against the reporting user.

8. Enforcement Actions
Depending on the nature and severity of the violation, Elunara may take one or more of the following actions:

Remove or restrict access to the content
Issue warnings or notices to the user
Temporarily suspend user access
Permanently terminate user accounts
Report content or users to law enforcement or regulatory authorities where required

9. Legal Compliance (India)
This policy is framed in accordance with applicable Indian laws, including but not limited to:

The Information Technology Act, 2000
The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021
Bharatiya Nyay Sanhita, 2023 (where applicable)

Elunara acts as an intermediary and follows due diligence obligations as prescribed under Indian law.

10. No Liability for User Content
Elunara does not endorse, verify, or guarantee the accuracy, legality, or appropriateness of user-generated or AI-generated content. To the fullest extent permitted by law, Elunara shall not be liable for any loss, harm, or damage arising from such content.

11. Policy Updates
Elunara may update or modify this Content Moderation Policy from time to time to reflect changes in law, technology, or platform practices. Continued use of the platform after such updates constitutes acceptance of the revised policy.

12. Contact and Grievance Redressal
For questions, concerns, or reports related to content moderation, users may contact Elunara through the official grievance redressal mechanism provided on the website.`,
  },
  {
    title: "Academic Integrity Policy",
    content: `ELUNARA – ACADEMIC INTEGRITY POLICY
Last Updated: March 31, 2026

1. Purpose
Elunara is committed to promoting ethical learning practices, honesty, and academic responsibility. This Academic Integrity Policy sets out the standards of conduct expected from users while accessing and using the Elunara platform. The objective is to ensure that Elunara is used as a legitimate learning support tool and not as a substitute for original academic effort.

2. Scope
This Policy applies to all users of Elunara, including students, educators, professionals, and any other individuals accessing the platform through the website or associated services. It applies to all content generated, accessed, or used through Elunara.

3. Learning Aid Disclaimer
Elunara is designed solely as a learning support and guidance tool. It is not intended to be used as a shortcut for completing academic assignments, examinations, research submissions, or any other evaluative academic work.

Use of Elunara does not replace:

Independent thinking
Original writing
Critical analysis
Compliance with institutional academic standards

Users remain fully responsible for the academic work they submit to their institutions or employers.

4. User Obligations
By using Elunara, users agree to adhere to the following obligations:

4.1. Original Work
Users must ensure that all academic submissions prepared with assistance from Elunara are substantially original and reflect their own understanding and effort.

4.2. Proper Disclosure and Citation
Where required by institutional rules, academic guidelines, or applicable policies, users must clearly disclose and cite the use of AI-assisted tools, including Elunara.

4.3. Compliance with Institutional Rules
Users must strictly follow the academic integrity codes, honor codes, examination rules, and assessment guidelines prescribed by their respective schools, colleges, universities or professional bodies.

4.4. Prohibited Uses
Users must not:

Submit AI-generated content as their own work without disclosure where disclosure is required.
Use Elunara to engage in plagiarism, contract cheating, impersonation, or exam malpractice.
Use the platform to bypass assessment safeguards or academic evaluation processes.

5. Plagiarism and Misconduct
Elunara does not endorse plagiarism or academic dishonesty in any form. Users are solely responsible for ensuring that their submissions do not violate plagiarism standards, copyright laws, or institutional policies.

Elunara does not guarantee that content generated through the platform is plagiarism-free or suitable for direct submission.

6. Monitoring and Detection
Elunara reserves the right to:

Monitor usage patterns for misuse or policy violations.
Investigate suspected breaches of this Policy.
Cooperate with educational institutions, regulatory bodies, or lawful authorities where required.

Such monitoring will be conducted in accordance with applicable data protection and privacy laws.

7. Enforcement and Consequences
Violation of this Academic Integrity Policy may result in one or more of the following actions, at Elunara's sole discretion:

Warning or formal notice
Temporary suspension of user access
Permanent termination of the user account
Restriction of access to specific features
Reporting of serious or repeated violations to educational institutions, employers, or authorities where legally permissible

Repeated or severe violations will be treated as a material breach of Elunara's Terms of Service.

8. Legal and Regulatory Compliance (India)
This Policy is framed in alignment with applicable Indian laws and regulations, including but not limited to:

The Information Technology Act, 2000 and rules made thereunder
University Grants Commission (UGC) Regulations on Promotion of Academic Integrity and Prevention of Plagiarism, 2018 (as amended)
Applicable institutional and professional academic codes

Users are responsible for understanding and complying with the academic integrity laws and regulations applicable to their jurisdiction and institution.

9. Limitation of Liability
Elunara shall not be held responsible for:

Academic penalties imposed on users by institutions
Rejection of submissions, grading outcomes, or disciplinary actions
Misuse of the platform contrary to this Policy

All academic and professional consequences arising from the use of Elunara rest solely with the user.

10. Policy Updates
Elunara reserves the right to update or modify this Academic Integrity Policy at any time. Continued use of the platform after changes are posted constitutes acceptance of the revised Policy.

11. Contact and Reporting
If you have questions regarding this Policy or wish to report suspected misuse, please contact:

Email: security@elunara.ai
Grievance Officer: As specified under the Grievance Redressal Policy`,
  },
  {
    title: "Advertising & Promotional Policy",
    content: `Advertising & Promotional Policy
Last Updated: March 31, 2026

This Advertising & Promotional Policy governs how advertising, sponsorships, and promotional communications are displayed and managed on the Elunara platform. Elunara is committed to maintaining transparency, user trust, and compliance with applicable Indian laws while ensuring a fair and ethical advertising environment.

1. Purpose of the Policy
The purpose of this policy is to:

Ensure transparency in all advertising and promotional activities on the Platform
Protect users from misleading, deceptive, or inappropriate advertisements
Define user rights and controls over promotional communications
Comply with applicable Indian laws, regulations, and industry standards

2. Scope
This policy applies to:

All advertisements, sponsorships, promotions, and marketing communications displayed on Elunara
Promotional emails, notifications, messages, and in-app announcements
Third-party advertisements or sponsored content, if any, hosted or displayed on the Platform

3. Transparency in Advertising
Elunara is committed to honest and transparent advertising practices.

Sponsored content, paid partnerships, or promotional material will be clearly and prominently identified as "Sponsored", "Advertisement", or "Promotional Content"
Advertisements will not be disguised as educational content, system messages, or user communications
Any material connection between Elunara and advertisers will be disclosed where required

4. Acceptable Advertising Standards
All advertisements and promotions displayed on Elunara must:

Be lawful, truthful, and not misleading
Be appropriate for the Platform's user base, including students and educators
Respect public decency and moral standards
Not exploit user trust or lack of technical knowledge

Elunara reserves the right to review, approve, reject, modify, or remove any advertisement at its sole discretion.

5. Prohibited Advertising Content
Elunara does not permit advertisements or promotions that:

Are illegal under Indian law
Promote hate speech, discrimination, violence, or harassment
Contain false claims, deceptive practices, or unverified guarantees
Promote tobacco, narcotics, illegal substances, or unlawful services
Contain obscene, defamatory, or sexually explicit material
Target minors with inappropriate products or services
Infringe intellectual property rights

6. User Control Over Promotional Communications
Elunara respects user preferences and provides control over promotional messaging.

Users may opt out of promotional emails, messages, or notifications at any time through account settings or unsubscribe links
Transactional or service-related communications are not considered promotional and may continue even after opting out
Opt-out requests will be processed within a reasonable timeframe

7. Third-Party Advertisements
Elunara may display advertisements from third-party partners
Elunara does not endorse or guarantee third-party products or services unless explicitly stated
Users interacting with third-party advertisements do so at their own discretion and risk
Third-party advertisers are responsible for the accuracy, legality, and compliance of their content

8. Data Usage for Advertising
Elunara does not sell personal data for advertising purposes
Any use of user data for promotional targeting will comply with Elunara's Privacy Policy and applicable laws
Sensitive personal data will not be used for advertising without explicit consent

9. Compliance with Indian Laws
This policy is governed by and complies with applicable Indian laws, including but not limited to:

The Information Technology Act, 2000
The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021
The Consumer Protection Act, 2019

10. Enforcement and Violations
Advertisements violating this policy may be removed immediately without notice
Repeat or serious violations may result in termination of advertising agreements
Elunara reserves the right to report unlawful advertisements to relevant authorities

11. Limitation of Liability
Elunara shall not be liable for any loss, damage, or dispute arising from:

User reliance on third-party advertisements
Interactions with advertisers outside the Platform
Accuracy or performance of advertised products or services

12. Policy Updates
Elunara may update this policy from time to time to reflect legal, operational, or regulatory changes. Continued use of the Platform after such updates constitutes acceptance of the revised policy.

13. Contact Information
For questions, concerns, or complaints related to advertising or promotions, users may contact Elunara through the official contact details provided on the Platform.`,
  },
  {
    title: "Refund Policy",
    content: `ELUNARA – REFUND POLICY
Last Updated: 31 March, 2026

This Refund and Cancellation Policy ("Policy") governs the circumstances under which refunds, cancellations, or credits may be issued for services offered through Elunara, an AI-powered educational platform providing personalized, ethical, and multilingual learning experiences primarily for management education. This Policy forms an integral part of Elunara's Terms of Service.

1. Definitions
"Platform" means the Elunara website, mobile application, and related digital interfaces.
"User" means any individual or entity that accesses or uses the Platform.
"Services" means AI-assisted learning tools, courses, academic content, subscriptions, assessments, mentorship modules, or any other educational offerings made available on Elunara.
"Subscription" means a paid plan granting access to specified Services for a defined period.
"Fee" means the amount paid by a User for accessing paid Services on the Platform.
"Billing Cycle" means the recurring period for which a Subscription Fee is charged.
"Refund" means the reversal of a Fee paid by the User, subject to the terms of this Policy.

2. General Policy
All purchases made on Elunara are final unless expressly stated otherwise in this Policy or required under applicable law. Users are encouraged to review the description of Services carefully before making any payment.

Elunara reserves the right to grant or deny refunds strictly in accordance with this Policy.

3. Subscription-Based Services

3.1 Cancellation by User
Users may cancel their Subscription at any time through their account settings. Upon cancellation:

Access to paid Services will continue until the end of the current Billing Cycle.
No refund shall be issued for any unused portion of the Subscription period.

3.2 Auto-Renewal
Subscriptions may renew automatically unless cancelled prior to the renewal date. Fees charged due to failure to cancel before renewal are non-refundable.

4. One-Time Purchases and Programs
Fees paid for one-time purchases, including but not limited to courses, workshops, certifications, assessments, or mentoring sessions, are non-refundable once access has been granted or the Service has commenced.

5. Free Trials and Promotional Access
If Elunara offers free trials or promotional access:

No charges will be applied during the free trial period.
Once the free trial converts into a paid Subscription, the applicable Fee shall be charged and shall be non-refundable.

6. Exceptions and Refund Eligibility
A refund may be considered only in the following limited circumstances:

Duplicate or erroneous charges due to a technical error attributable to Elunara
Failure of the Platform to provide access to paid Services due to a verified technical issue not caused by the User
Any refund mandated by applicable consumer protection laws

In such cases, refunds, if approved, shall be processed using the original method of payment within a reasonable period.

7. Non-Refundable Situations
Refunds shall not be provided for:

Dissatisfaction with AI-generated outputs or learning outcomes
Change of mind after purchase
Lack of usage or partial usage of the Services
Academic performance, grades, or professional outcomes
Suspension or termination of account due to violation of Elunara's Terms of Service

8. Institutional and Enterprise Users
Refund terms for institutions, universities, corporate clients, or bulk licenses shall be governed by separate written agreements. This Policy shall not apply where a specific contract provides otherwise.

9. Chargebacks and Disputes
Users agree to contact Elunara first to resolve any payment-related concerns. Initiating chargebacks or payment disputes without prior communication may result in suspension or termination of access to the Platform.

10. Changes to the Policy
Elunara reserves the right to amend this Policy at any time. Changes shall be effective upon publication on the Platform. Continued use of the Services after such changes constitutes acceptance of the revised Policy.

11. Governing Law and Jurisdiction
This Policy shall be governed by and construed in accordance with the laws of India. Courts in India shall have exclusive jurisdiction over any disputes arising under this Policy.

12. Contact Information
For refund-related queries or support, Users may contact:

Elunara
security@elunara.ai

By using Elunara and making any payment on the Platform, you acknowledge that you have read, understood, and agreed to this Refund and Cancellation Policy.`,
  },
  {
    title: "Grievance Redressal Policy",
    content: `ELUNARA – GRIEVANCE REDRESSAL POLICY
Last Updated: March 31, 2026

1. Purpose
Elunara is committed to providing a safe, transparent, and user-friendly digital platform. This Grievance Redressal Policy sets out the mechanism through which users may raise concerns, complaints, or grievances related to the use of the Elunara website, including issues relating to platform services, data protection, content, or policy compliance.

This policy is framed in accordance with applicable laws in India, including the Information Technology Act, 2000, the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, and the Digital Personal Data Protection Act, 2023, where applicable.

2. Scope
This policy applies to all users, visitors, and registered members accessing or using the Elunara website. It covers grievances relating to, but not limited to:

Use or functionality of the platform
Access to services or content
Data protection and privacy concerns
Alleged violation of Elunara's policies or terms
Unauthorized use, misuse, or abuse of the platform
Any other issue affecting a user's lawful rights or interests

3. Definition of Grievance
For the purpose of this policy, a "grievance" means any complaint, concern, or dissatisfaction expressed by a user in relation to the Elunara website, its services, content, or handling of personal data.

4. Appointment of Grievance Officer
In compliance with Rule 3(2) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, Elunara has appointed a Grievance Officer to address user grievances in a timely and effective manner.

Grievance Officer Details:

Name: …………………..
Designation: Grievance Officer
Email: security@elunara.ai
Address: [registered office address of Elunara]

The Grievance Officer shall be responsible for acknowledging, examining and resolving grievances received from users.

5. How to Raise a Grievance
Users may submit their grievances by sending an email to the Grievance Officer at the email address mentioned above. The grievance communication should include:

Full name of the user
Registered email address or contact details
Clear description of the grievance
Relevant screenshots, documents, or supporting information, if any

Anonymous or vague complaints without sufficient details may not be processed.

6. Acknowledgement and Resolution Timeline
All grievances shall be acknowledged within 24 to 48 hours of receipt.
Elunara shall make best efforts to resolve the grievance within 15 (fifteen) days from the date of receipt, or within such time as prescribed under applicable law.
In cases requiring additional investigation or information, the user may be contacted for clarification.

7. Data Protection and Privacy-Related Grievances
Grievances relating to personal data, including collection, storage, processing, sharing, or deletion of personal data, shall be handled in accordance with Elunara's Privacy Policy and the Digital Personal Data Protection Act, 2023.

Users may specifically raise concerns regarding:

Unauthorized access to personal data
Inaccurate or outdated personal data
Withdrawal of consent
Data security incidents or breaches

8. Escalation
If any user is not satisfied with the resolution provided, they may escalate the matter by replying to the original grievance communication with additional details or clarification. Elunara will review the grievance afresh and provide a reasoned response.

Nothing in this policy restricts a user's right to seek appropriate legal remedies under applicable Indian laws.

9. Limitation
Elunara shall not be responsible for grievances arising from:

Third-party websites, services, or links accessed through the platform
User-generated content posted by other users, except to the extent required under applicable law
Issues beyond the reasonable control of Elunara

10. Record Maintenance
Elunara shall maintain records of grievances received and actions taken for such period as required under applicable law, and may use such records for audit, compliance, or legal purposes.

11. Policy Updates
Elunara reserves the right to amend or update this Grievance Redressal Policy at any time to ensure compliance with legal requirements or operational needs. Any changes shall be effective upon publication on the website.

12. Governing Law and Jurisdiction
This Grievance Redressal Policy shall be governed by and construed in accordance with the laws of India. Courts having jurisdiction over the registered office of Elunara shall have exclusive jurisdiction over matters arising under this policy.`,
  },
  {
    title: "Accessibility & Inclusion Policy",
    content: `ACCESSIBILITY & INCLUSION POLICY
Last Updated: March 31, 2026

1. Purpose
Elunara is committed to providing an inclusive, accessible, and equitable digital experience for all users, regardless of ability, language, location, or technological constraints. This Accessibility & Inclusion Policy outlines Elunara's approach to ensuring that its platform is usable by individuals with diverse needs and abilities.

2. Scope
This Policy applies to:

The Elunara website and web based services
All digital content, features, and learning tools offered through the platform
Users accessing Elunara via desktop, mobile, or assistive technologies

3. Commitment to Inclusive Design
Elunara follows an inclusive design philosophy that prioritizes accessibility from the earliest stages of product development. Accessibility is treated as an ongoing responsibility rather than a one-time compliance exercise.

The platform is designed to support:

Users with visual, auditory, motor, cognitive, and learning disabilities
Users from diverse linguistic and cultural backgrounds
Users with limited access to high speed internet or advanced devices

4. Accessibility Features
To support accessibility and inclusion, Elunara currently provides or actively works toward the following features:

4.1. Multilingual Support
Interface and content availability in multiple languages where feasible
Progressive expansion of regional language support to improve access for non English users

4.2. Low Bandwidth Optimization
Optimized page loading and reduced data heavy elements
Compatibility with slower internet connections and basic devices
Efficient use of media to ensure functionality in bandwidth constrained environments

4.3. Assistive Technology Compatibility
Support for screen readers and keyboard navigation
Logical content structure to improve readability and navigation
Descriptive text for interactive elements where applicable

4.4. Continuous Accessibility Improvements
Periodic accessibility reviews and audits
Updates based on user feedback and evolving best practices
Ongoing enhancement of usability and readability

5. Standards and Guidelines
Elunara aims to align its accessibility practices with recognized standards, including:

Web Content Accessibility Guidelines (WCAG) 2.1, Level AA, where reasonably practicable
Global best practices for inclusive digital learning platforms

These standards guide platform design, content structure, and feature development.

6. Legal and Regulatory Compliance (India)
Elunara endeavors to comply with applicable Indian laws and regulations related to accessibility and digital inclusion, including but not limited to:

The Rights of Persons with Disabilities Act, 2016 Supporting equal access to digital services and information for persons with disabilities
Information Technology Act, 2000 and applicable rules Governing electronic content, accessibility obligations, and digital service delivery

Where required, Elunara will update its accessibility measures to align with future legal or regulatory developments.

7. User Responsibilities
While Elunara strives to make the platform accessible, users are encouraged to:

Use supported browsers, devices, and assistive technologies
Keep their systems updated to ensure optimal compatibility
Report accessibility barriers encountered on the platform

8. Feedback and Support
Elunara values user feedback as a key driver of accessibility improvement. Users who face accessibility challenges or have suggestions may contact the designated support or grievance channel listed on the website.

All accessibility related concerns will be reviewed in good faith and addressed within a reasonable timeframe.

9. Limitations
Despite best efforts, some features or third party integrations may have accessibility limitations. Elunara does not guarantee that every aspect of the platform will be fully accessible at all times but commits to continuous improvement and reasonable accommodation wherever feasible.

10. Policy Updates
This Policy may be updated periodically to reflect:

Technological advancements
Changes in legal or regulatory requirements
Improvements in accessibility standards or platform functionality

Updated versions will be published on the Elunara website and will become effective upon posting.

11. Contact Information
For accessibility related queries, feedback, or assistance, users may refer to the contact or grievance details provided on the Elunara website.`,
  },
  {
    title: "Ethical AI & Responsible Use Policy",
    content: `ELUNARA - ETHICAL AI & RESPONSIBLE USE POLICY
Last Updated: March 31, 2026

1. PURPOSE
This Ethical AI & Responsible Use Policy ("Policy") forms an integral part of Elunara's Platform Policies and shall be read in conjunction with the Terms of Service, Privacy Policy and other applicable platform policies. This Policy is legally binding on all users, employees, consultants, partners, vendors and third parties who access, develop, deploy or use any Artificial Intelligence (AI) or automated features provided by Elunara.

Elunara is an AI-powered educational platform focused on management education. Accordingly, this Policy emphasises ethical, lawful, transparent and responsible use of AI in academic, professional and learning environments.

2. DEFINITIONS
For the purposes of this Policy:

(a) "AI Systems" means machine learning models, algorithms, generative AI tools, automated or semi-automated decision-support systems, and related technologies used by Elunara.
(b) "Bias" means systematic and unfair discrimination or skewed outcomes affecting individuals or groups.
(c) "Personal Data" shall have the meaning assigned to it under the DPDP Act.
(d) "Processing" includes collection, use, storage, training, inference, sharing, disclosure, retention and deletion.
(e) "User" or "You" means any individual or entity accessing or using the Platform, including students, educators, institutions and visitors.

2. SCOPE AND APPLICABILITY
This Policy applies to:

All AI-powered tools, models, algorithms and automated systems developed or deployed by Elunara.
AI features used for content generation, learning assistance, assessment support, analytics or recommendations.
Internal AI systems used for operations, moderation, security or decision support.
Third-party AI systems integrated into the Elunara platform.

3. CORE ETHICAL PRINCIPLES OF ETHICAL
Elunara's AI Systems are governed by the following core principles:

3.1. Human-Centric AI
Elunara's AI systems are designed to assist learning and productivity, not to replace human intelligence, academic effort or institutional decision-making. Human oversight shall be maintained, particularly in high-impact or sensitive contexts.

3.2. Fairness and Bias Mitigation
Elunara undertakes reasonable and ongoing efforts to identify, assess and mitigate algorithmic bias. AI systems shall not discriminate on the basis of gender, caste, religion, ethnicity, disability, age, socio-economic status or any other protected characteristic under applicable law.

3.3. Transparency
AI-generated outputs, recommendations, or automated actions shall be clearly identifiable as such. Users shall be informed when they are interacting with or relying upon AI-driven features.

3.4. Accountability
Elunara retains accountability for the design and deployment of its AI systems. Clear internal ownership and escalation mechanisms are maintained for AI-related decisions, errors, or impacts.

3.5. Safety, Reliability, and Accuracy
AI systems are tested, monitored, and periodically reviewed to reduce risks of harmful, misleading, or inaccurate outputs. However, AI outputs are probabilistic in nature and should not be treated as infallible.

4. RESPONSIBLE USE BY USERS
AI features provided by Elunara are intended strictly as learning aids and decision support tools. Users acknowledge and agree that:

AI outputs do not constitute professional, legal, academic, or institutional advice
Final responsibility for academic submissions, decisions, and actions remains with the user
AI assistance must be used in compliance with institutional rules and academic integrity requirements

5. PROHIBITED USES
Users shall not use Elunara's AI systems for any unlawful, unethical, or prohibited purpose, including but not limited to:

Academic cheating, impersonation, or submission of AI-generated content as original work where prohibited.
Circumventing examination, assessment, or institutional rules.
Generating fraudulent, deceptive, defamatory, or misleading content.
Harassment, hate speech, discrimination, or abuse.
Creation or dissemination of illegal content.
Manipulation of users, institutions, or outcomes through deceptive AI use
Reverse engineering, bypassing safeguards, or unauthorised access to AI systems.

Violation of this section may result in suspension, termination, reporting to educational institutions, or legal action, as applicable.

6. DATA GOVERNANCE AND PRIVACY

6.1. Lawful Processing
All personal data used in AI systems shall be processed in accordance with applicable data protection laws of India.

6.2. Applicable Indian Laws
Elunara's AI and data practices are aligned with, inter alia:

The Information Technology Act, 2000
Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011
The Digital Personal Data Protection Act, 2023
Consumer Protection Act, 2019
Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021

6.3. Data Minimisation and Security
Only data necessary for legitimate purposes is used. Appropriate technical and organisational security measures are implemented to protect data used in AI systems.

7. AUTOMATED DECISION-MAKING AND HUMAN OVERSIGHT
Elunara does not rely solely on automated decision-making for outcomes that significantly affect user rights, access, or academic standing.
Human review mechanisms are maintained for high-impact decisions.
Users may request clarification or review of certain AI-driven outcomes, subject to platform capabilities.

8. THIRD-PARTY AI SYSTEMS
Where third-party AI tools or services are used:

Reasonable due diligence is undertaken.
Contractual safeguards relating to privacy, security, and ethical use are imposed.
Elunara is not responsible for unauthorised or unlawful use of third-party AI systems beyond its reasonable control.

9. MONITORING, AUDIT, AND CONTINUOUS IMPROVEMENT
Elunara may:

Monitor AI system performance and usage patterns
Conduct internal reviews or audits
Update models, safeguards, or controls to address emerging risks
Modify or withdraw AI features where necessary

10. LIMITATION OF LIABILITY
AI-generated outputs are provided on an "as is" and "as available" basis. To the maximum extent permitted by law, Elunara disclaims liability for:

Errors, omissions, or inaccuracies in AI outputs
User reliance on AI outputs for academic or professional decisions
Misuse or unauthorised use of AI systems by users or third parties

11. ENFORCEMENT
Non-compliance with this Policy may result in:

Warning or restriction of access
Suspension or termination of user accounts
Reporting to relevant institutions or authorities
Civil or criminal action where required under law

12. POLICY UPDATES
Elunara reserves the right to update or modify this Policy at any time. Updated versions shall be published on the Platform. Continued use of the Platform constitutes acceptance of the revised Policy.

13. GOVERNING LAW AND JURISDICTION
This Policy shall be governed by and construed in accordance with the laws of India. Courts having jurisdiction at [City, India] shall have exclusive jurisdiction.

14. CONTACT AND GRIEVANCE REDRESSAL
For concerns, questions, or reporting misuse of AI systems:

Email: security@elunara.ai

Grievances shall be addressed within the timelines prescribed under applicable Indian law.`,
  },
];

const renderFormattedContent = (content) => {
  const lines = content.split("\n");

  // Find the first non-empty line index — used to detect a Title Case doc title
  const firstNonEmptyIndex = lines.findIndex((l) => l.trim() !== "");

  return lines.map((line, i) => {
    const trimmed = line.trim();

    // Empty line → spacer
    if (trimmed === "") {
      return <View key={i} style={styles.lineSpacer} />;
    }

    // A "heading-like" line should not end with sentence-terminating punctuation
    const looksLikeSentence = /[.;!?]$/.test(trimmed);

    // Document title (all caps + dash/em-dash + more caps)
    if (/^[A-Z][A-Z\s]+[–-]\s+[A-Z]/.test(trimmed)) {
      return (
        <Text key={i} style={styles.docTitle}>
          {trimmed}
        </Text>
      );
    }

    // Title Case doc title (first non-empty line, ≤8 words, no sentence punctuation)
    if (
      i === firstNonEmptyIndex &&
      !looksLikeSentence &&
      trimmed.split(/\s+/).length <= 8 &&
      /^[A-Z]/.test(trimmed)
    ) {
      return (
        <Text key={i} style={styles.docTitle}>
          {trimmed}
        </Text>
      );
    }

    // "Last Updated:" line
    if (/^Last Updated:/i.test(trimmed)) {
      return (
        <Text key={i} style={styles.metaText}>
          {trimmed}
        </Text>
      );
    }

    // Sub-numbered heading e.g. "3.1 Information Provided by You" or "3.1. Essential Cookies"
    if (/^\d+\.\d+\.?\s+\S/.test(trimmed) && !looksLikeSentence) {
      return (
        <Text key={i} style={styles.subHeading}>
          {trimmed}
        </Text>
      );
    }

    // Main numbered heading e.g. "1. DEFINITIONS"
    if (/^\d+\.\s+[A-Z]/.test(trimmed) && !looksLikeSentence) {
      return (
        <Text key={i} style={styles.mainHeading}>
          {trimmed}
        </Text>
      );
    }

    // All-caps standalone heading e.g. "OBJECTIVE"
    if (/^[A-Z][A-Z\s&]{2,}$/.test(trimmed)) {
      return (
        <Text key={i} style={styles.mainHeading}>
          {trimmed}
        </Text>
      );
    }

    // Lettered sub-heading e.g. "a) Purpose Limitation"
    if (/^[a-z]\)\s+[A-Z]/.test(trimmed) && !looksLikeSentence) {
      return (
        <Text key={i} style={styles.subHeading}>
          {trimmed}
        </Text>
      );
    }

    // Default paragraph
    return (
      <Text key={i} style={styles.accordionContentText}>
        {trimmed}
      </Text>
    );
  });
};

const AccordionItem = ({ index, title, content, isOpen, onToggle }) => {
  return (
    <Animated.View
      layout={LinearTransition.duration(250)}
      style={styles.accordionWrapper}
    >
      <TouchableOpacity
        activeOpacity={0.85}
        onPress={onToggle}
        style={styles.accordionHeader}
      >
        <View style={styles.numberBadge}>
          <Text style={styles.numberBadgeText}>{index + 1}</Text>
        </View>
        <Text style={styles.accordionTitle} numberOfLines={2}>
          {title}
        </Text>
        {isOpen ? (
          <ChevronUp
            size={32}
            color={appColors.navyBlueShade}
            strokeWidth={1}
          />
        ) : (
          <ChevronDown
            size={32}
            color={appColors.navyBlueShade}
            strokeWidth={1}
          />
        )}
      </TouchableOpacity>
      {isOpen && (
        <Animated.View
          entering={FadeIn.duration(200)}
          exiting={FadeOut.duration(150)}
          style={styles.accordionContent}
        >
          {renderFormattedContent(content)}
        </Animated.View>
      )}
    </Animated.View>
  );
};

const TermsOfUse = ({ handleScroll }) => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggle = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#fff" />
      <ScrollView
        onScroll={handleScroll}
        style={styles.scrollView}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View
          style={{
            backgroundColor: "#F3F3F3",
            paddingHorizontal: 20,
            paddingVertical: 20,
          }}
        >
          <Text style={styles.headerLabel}>Updated: 24 July 2025</Text>
          <Text style={styles.mainTitle}>Terms of use</Text>
          <Text style={styles.introText}>
            By using our app and services, you agree to the following Terms of
            Use. Please read them carefully.
          </Text>
        </View>

        {/* Accordions */}
        <View style={styles.accordionList}>
          {accordionData.map((item, index) => (
            <AccordionItem
              key={index}
              index={index}
              title={item.title}
              content={item.content}
              isOpen={openIndex === index}
              onToggle={() => toggle(index)}
            />
          ))}
        </View>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  headerLabel: {
    fontSize: 13,
    color: "#666666",
    marginBottom: 8,
    fontWeight: "400",
    fontFamily: "Mukta-Regular",
  },
  mainTitle: {
    fontSize: scaleFont(24),
    fontFamily: "Mukta-Bold",
    color: "#1A1A1A",
    marginBottom: 12,
    lineHeight: 36,
  },
  introText: {
    fontSize: scaleFont(14),
    fontFamily: "Mukta-Regular",
    color: "#666666",
    lineHeight: 24,
  },
  accordionList: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 14,
  },
  accordionWrapper: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D3DAE5",
    overflow: "hidden",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 18,
    gap: 12,
  },
  numberBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appColors.navyBlueShade,
    alignItems: "center",
    justifyContent: "center",
  },
  numberBadgeText: {
    color: "#FFFFFF",
    fontSize: scaleFont(13),
    fontFamily: "Mukta-Bold",
    fontWeight: "600",
  },
  accordionTitle: {
    flex: 1,
    fontSize: scaleFont(15),
    fontFamily: "Mukta-Bold",
    fontWeight: "600",
    color: "#1A1A1A",
  },
  accordionContent: {
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: "#F1F1F1",
    marginTop: 4,
  },
  accordionContentText: {
    fontSize: scaleFont(14),
    fontFamily: "Mukta-Regular",
    color: "#5E5E5E",
    lineHeight: 22,
  },
  docTitle: {
    fontSize: scaleFont(18),
    fontFamily: "Mukta-Bold",
    fontWeight: "700",
    color: "#1A1A1A",
    marginTop: 4,
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  metaText: {
    fontSize: scaleFont(12),
    fontFamily: "Mukta-Regular",
    color: "#888888",
    fontStyle: "italic",
    marginBottom: 6,
  },
  mainHeading: {
    fontSize: scaleFont(16),
    fontFamily: "Mukta-Bold",
    fontWeight: "700",
    color: "#1A1A1A",
    marginTop: 14,
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  subHeading: {
    fontSize: scaleFont(14),
    fontFamily: "Mukta-Bold",
    fontWeight: "600",
    color: "#1A1A1A",
    marginTop: 8,
    marginBottom: 2,
  },
  lineSpacer: {
    height: 8,
  },
  bottomSpacer: {
    height: 20,
  },
});

export default TermsOfUse;
