import { handleCreateChatWithAI, handleGetAllDetailsOfChatByID, handleGetAllRecentChats, handleGetAllSubjectsForChat, handleGetAllTopicsOfSelectedSubjects, handleRenameAndUpdateChatTitle, handlePinOrUnpinChat, handleArchiveOrUnarchiveChat, handleDeleteChat, handleUndoDeleteChat, handleFetchAllUserChatsAvailable, handleBulkOperationsForChats, handleFetchAllUserRoomsAvailable, handlePostAddToNotes, handlePostRemoveFromNotes, handleSendPromptAndGetMessageFromAI, handleUpdateUserMessageForRegeneration, handleRegenerateAIResponse, handleGetAllMessagesOfParticularChat, handleSwitchVersionsOfAIResponse, handleCompareAIResponses, handleStoreCompareResponses, handleCompareAIResponseStyles, handleStoreCompareStyleResponses, handleCompareAIResponsesFirst, handleCompareAIResponsesSecond, handleCompareAIResponseStylesFirst, handleCompareAIResponseStylesSecond } from "./apiExtraReducerHandlers/chatsHandlers";
import { handleGetAllCitiesAvailable, handleGetAllCountriesAvailable, handleGetAllGendersAvailable, handleGetAllUniversitiesAvailable, handleGetAllDegreeProgramsAvailable, handleGetAllSpecializationsAvailable, handleGetAllGeneralSettings, handleGetAllLanguagesAvailable, handleGetAllLLMsAvailable, handleGetAllPersonalisationsSettings, handleRestoreAllGeneralSettings, handleUpdateGeneralSettings, handleUpdatePersonalisationsSettings, handleGetAllProfileInfos, handleUpdateProfileName, handleUpdateProfileImage, handleUpdateProfileAvatarImage, handleFetchResponseStylesAvailable, handleFetchCitationFormatsAvailable } from "./apiExtraReducerHandlers/settingsHandlers";

export const settingsHandlersFunctions = {
  // get all settings of sections
  getAllGeneralSettings:handleGetAllGeneralSettings,
  getAllPersonalisationsSettings:handleGetAllPersonalisationsSettings,
  getAllProfileInfos:handleGetAllProfileInfos,
  // get master datas
  getAllLLMsAvailable:handleGetAllLLMsAvailable,
  getAllLanguagesAvailable:handleGetAllLanguagesAvailable,
  getAllCountriesAvailable:handleGetAllCountriesAvailable,
  getAllCitiesAvailable:handleGetAllCitiesAvailable,
  getAllGendersAvailable:handleGetAllGendersAvailable,
  getAllUniversitiesAvailable:handleGetAllUniversitiesAvailable,
  getAllDegreeProgramsAvailable:handleGetAllDegreeProgramsAvailable,
  getAllSpecializationsAvailable:handleGetAllSpecializationsAvailable,
  fetchResponseStylesAvailable:handleFetchResponseStylesAvailable,
  fetchCitationFormatsAvailable:handleFetchCitationFormatsAvailable,
  // update or change settings
  updateGeneralSettings:handleUpdateGeneralSettings,
  restoreAllGeneralSettings:handleRestoreAllGeneralSettings,
  updatePersonalizationSettings:handleUpdatePersonalisationsSettings,
  // profile section manage
  updateProfileName: handleUpdateProfileName,
  updateProfileImage: handleUpdateProfileImage,
  updateProfileAvatarImage: handleUpdateProfileAvatarImage,
}


export const chatsHandlersFunctions = {
  getAllRecentChats:handleGetAllRecentChats,
  getAllDetailsOfChatByID:handleGetAllDetailsOfChatByID,
  //get master datas
  getAllSubjectsForChat:handleGetAllSubjectsForChat,
  getAllTopicsOfSelectedSubjects:handleGetAllTopicsOfSelectedSubjects,

  createChatWithAI:handleCreateChatWithAI,
  sendPromptAndGetMessageFromAI: handleSendPromptAndGetMessageFromAI,
  getAllMessagesOfParticularChat:handleGetAllMessagesOfParticularChat,
  //Chat Notes
  postAddToNotes: handlePostAddToNotes,
  postRemoveFromNotes: handlePostRemoveFromNotes,
  renameAndUpdateChatTitle:handleRenameAndUpdateChatTitle,
  pinOrUnpinChat:handlePinOrUnpinChat,
  archiveOrUnarchiveChat:handleArchiveOrUnarchiveChat,
  deleteChat:handleDeleteChat,
  undoDeleteChat:handleUndoDeleteChat,
  fetchAllUserChatsAvailable:handleFetchAllUserChatsAvailable,
  bulkOperationsForChats:handleBulkOperationsForChats,
  fetchAllUserRoomsAvailable:handleFetchAllUserRoomsAvailable,
  //Message editing and regeneration
  updateUserMessageForRegeneration:handleUpdateUserMessageForRegeneration,
  regenerateAIResponse:handleRegenerateAIResponse,
  switchVersionsOfAIResponse:handleSwitchVersionsOfAIResponse,
  compareAIResponses:handleCompareAIResponses,
  storeCompareResponses:handleStoreCompareResponses,
  compareAIResponseStyles:handleCompareAIResponseStyles,
  storeCompareStyleResponses:handleStoreCompareStyleResponses,
  compareAIResponsesFirst:handleCompareAIResponsesFirst,
  compareAIResponsesSecond:handleCompareAIResponsesSecond,
  compareAIResponseStylesFirst:handleCompareAIResponseStylesFirst,
  compareAIResponseStylesSecond:handleCompareAIResponseStylesSecond
}

