export const chatsStates = {
  // Chat data
  allChatsDatas: {
    allRecentChats: [],
    currentActionChatDetails: {},
    allSubjectsAvailable: [],
    allTopicsOfSelectedSubjects: [],
    createdChatDetails: {},
    allUserChatsAvailable: [],
    allUserRoomsAvailable: [],
    lastBulkOperationInfo: null,
    chatMessages: {},
    aiMessageContent: null,
    regeneratedResponse: {},
    switchedVersionData: {},
  },
  // Loader states
  loaderStates: {
    isAllRecentChatsFetched: null,
    isChatCreatedWithAI: null,
    isChatTitleUpdated: null,
    isChatPinUnpinUpdated: null,
    isChatArchiveUnarchiveUpdated: null,
    isChatDeleted: null,
    isChatDeleteUndone: null,
    isAllUserChatsFetched: null,
    isAllUserRoomsFetched: null,
    isBulkOperationCompleted: null,
    isAddToNotesPending: null,
    isRemoveFromNotesPending: null,
    isMessagesFetched: null,
    isTopicsOfSelectedSubjectsFetched: null,
    isUserMessageUpdated: null,
    isAIResponseRegenerated: null,
    isAllMessagesOfChatFetched: null,
    isVersionSwitched: null,
  },
  // Action states for room operations
  addingToRoom: false,
  removingFromRoom: false,
};
