export const settingsStates = {
  fetchingAllGeneralSettings: false,
  allGeneralSettings: {
    notificationsSettings: {},
    preferredLLMs: {},
    responseLanguageSettings: {},
    regionSettings: {},
    adSettings: {},
    isAnythingChangedInGeneralSettings:false,
  },
  isGeneralSettingsRestored:null,
  settingsMasterDatas: {
    allLLMsAvailable: [],
    allLanguagesAvailable: [],
    allCountriesAvailable: [],
    allCitiesAvailable: [],
    allGendersAvailable:[],
    allUniversitiesAvailable:[],
    allDegreeProgramsAvailable:[],
    allSpecializationsAvailable:[],
    selectedCountryCode: null,
    isCountrySelectionChanged: false,
  },
  allPersonalisationsSettings:{
    personalInfos:{},
    academicCareer:{},
    learningDevices:{},
    isAnythingChangedInPersonalisationSettings:false,
  },
  allProfileInfos:{},
};
