export const toggleStates = {
      toggleChatHistorySidebar: false,
      toggleIsChattingWithAI:false,
      toggleChatMenuPopup:false,
      toggleAddItemsToInputPopup:false,
      toggleTopicsPopup:false,
      toggleToolsPopup:false,
      toggleToolsPopupStates:0,
      toggleKeyboardVisibilityOnChatScreen:false,
      toggleIsWaitingForResponse:false,
      toggleSubTopics:false,
      toggleDeleteChatConfirmPopup:false,
      toggleArchiveChatConfirmPopup:false,
      toggleDeleteChatPopup:false,
      toggleArchiveChatPopup:false,
      toggleRenameChatPopup:false,
      toggleUserMessageActionPopup:false,
      toggleChatActionsPopupOnLongPress:false,
      toggleAllChatsOptionsPopup:false,
      toggleAllRoomsOptionsPopup:false,
      toggleUnlockPremiumPopup:false,
      toggleResetSettingsPopup:false,
      toggleIsPaidOrProUser:false,
      toggleRoomCreationPopup:false,
      toggleAddedRoomDetails:false,
      toggleIsRoomEmpty:true,
      toggleLearningLabUnlockPopup:false,
      toggleProPlanUpgradePopup:false,
      toggleUnlockAnalyticsDashboardPopup:false,
      toggleUnlockMaxUploadLimitPopup:false,
      toggleUnlockNewChatPopup:false,
      toggleUnlockArchiveLimitPopup:false,
      toggleAdFreeExpPopup:false,
      toggleUnlockPersonalisationLimitPopup:false,
      toggleElunaraProWelcomePopup:false,
      toggleChatScreenGuideStart:false,
      toggleChangeResponseLLMWhileChatPopup:false,
      toggleChangeLangWhileChatPopup:false,
      toggleChangeResponseStyleWhileChatPopup:false,
      toggleCompareStyleState:false,
      toggleNotHelpfulFeedbackPopup:false,
      toggleAddExistingChatToRoomPopup:false,
      toggleAddChatToLearningLabPopup:false,
      toggleAddLinkPopup:false,
      toggleUpdateProfilePicPopup:false,
      isEditingUserMessage:false,
      // Room Tools Popup States
      toggleRoomToolsPopup:false,
      toggleRoomToolsPopupStates:0,
      // Room Chats Options Popup
      toggleRoomChatsOptionsPopup:false,
      // Remove from Room Confirmation Popup
      toggleRemoveFromRoomConfirmPopup:false,
      // Bulk Remove from Room Confirmation Popup
      toggleBulkRemoveFromRoomConfirmPopup:false,
      // Unsaved Changes Confirmation Popup
      toggleUnsavedChangesConfirmPopup:false,
      // No Balance Modal
      toggleNoBalanceModal:false,
      // Low Balance Modal
      toggleLowBalanceModal:false,
}