export const toggleStates = {
      toggleChatHistorySidebar: false,
      toggleIsChattingWithAI:false,
      toggleChatMenuPopup:false,
      toggleAddItemsToInputPopup:false,
      toggleTopicsPopup:false,
      toggleToolsPopup:false,
      toggleToolsPopupStates:0,
      toggleKeyboardVisibilityOnChatScreen:false,
      toggleIsWaitingForResponse:false,
      toggleSubTopics:false,
      toggleDeleteChatConfirmPopup:false,
      toggleRenameChatPopup:false,
      toggleUserMessageActionPopup:false,
      toggleChatActionsPopupOnLongPress:false,
      toggleAllChatsOptionsPopup:false,
      toggleUnlockPremiumPopup:false,
      toggleResetSettingsPopup:false,
      toggleIsPaidOrProUser:false,
      toggleRoomCreationPopup:false,
      toggleAddedRoomDetails:false,
      toggleIsRoomEmpty:true,
      toggleLearningLabUnlockPopup:false,
}