export const walletStates = {
  walletBalance: 0,
  isInitialRechargeCompleted: false,
  isPromotionalUser: false,
  promotionalDaysRemaining: 0,
  walletTransactions: [],
  isWalletInfoFetched: false,
  isTransactionsFetched: false,
  isPaymentLoading: false,
  isPaymentFulfilled: false,
  paymentUrl: null,
  isVerifyingPayment: true,
  verifyPaymentStatus: null,
  verifyPaymentMessage: null,
  // Threshold constants (not state, but accessible)
  FILE_FEATURE_THRESHOLD: 799,
  MIN_RECHARGE: 99,
  MAX_RECHARGE: 9999,
  INITIAL_RECHARGE: 999,
};
