import { StyleSheet, Dimensions, Platform } from "react-native";
import {
  moderateScale,
  scale,
  scaleFont,
  verticalScale,
} from "../../../utils/responsive";
import { appColors } from "../../../themes/appColors";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const createStyles = ({}) =>
  StyleSheet.create({
    chatHistorySidebarBackgroundWrapper: {
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT,
      position: "absolute",
      left: 0,
      top: 0,
      zIndex: 10,
    },
    chatHistorySidebarWrapper: {
      width: SCREEN_WIDTH * 0.75,
      height: SCREEN_HEIGHT,
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      backgroundColor: "white",
      position: "absolute",
      left: 0,
      zIndex: 20,
      flexDirection: "column",
      justifyContent: "space-between",
      alignItems: "center",
      elevation: 10,
      paddingTop: 40,
    },
    chatHistorySidebarHeader: {
      width: "100%",
      paddingHorizontal: 20,
      flexDirection: "column",
      alignItems: "center",
      gap: verticalScale(20),
    },
    sidebarTopImageMain: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-start",
      gap: 20,
      marginTop: 20,
    },
    searchInputMain: {
      width: "100%",
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderRadius: 16,
      borderColor: "#ABB8CC",
    },
    searchIcon: {
      position: "absolute",
      left: 10,
    },
    searchInput: {
      width: "90%",
      paddingLeft: 15,
      marginLeft: "auto",
    },
    newButtonsMain: {
      width: "100%",
      flexDirection: "column",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 20,
      borderBottomWidth: 1,
      borderColor: "#D3DAE5",
      paddingBottom: 20,
    },
    newChatBtn: {
      width: "100%",
      minHeight: verticalScale(36),
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 20,
      paddingHorizontal: 20,
      paddingVertical: 11,
      backgroundColor: "#EBF1FB",
      borderRadius: 12,
    },
    newLearningTabBtn: {
      width: "100%",
      height: verticalScale(36),
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 20,
      paddingHorizontal: 20,
    },
    btnTexts: {
      fontWeight: 600,
      fontSize: scaleFont(15),
    },
    chakraLogoSidebar: {
      height: verticalScale(32),
      width: verticalScale(32),
    },
    elunaraLogoSidebar: {
      height: verticalScale(32),
      width: verticalScale(95),
      marginLeft: 2,
    },
    chatHistorySidebarMiddle: {
      width: "100%",
      flex: 1,
      paddingHorizontal: 20,
    },
    pinnedSectionMain: {
      width: "100%",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      borderBottomWidth: 1,
      borderColor: "#D3DAE5",
      paddingBottom: 5,
    },
    pinnedBtn: {
      width: "100%",
      paddingVertical: 20,
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingLeft: 20,
      fontSize: moderateScale(10),
    },
    individualRecentChatsMain: {
      width: "100%",
      paddingLeft: 20,
      flexDirection: "column",
      justifyContent: "flex-start",
      gap: 8,
      alignItems: "flex-start",
    },
    individualRecentChats: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 15,
      paddingVertical: 10,
      marginLeft: 20,
    },
    individualPinnedChatsMain: {
      width: "90%",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingVertical: 10,
      paddingLeft: 20,
    },
    individualPinnedChats: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 15,
      paddingVertical: 10,
      paddingLeft: 20,
      borderLeftWidth: 1,
      borderColor: "#D3DAE5",
    },
    individualPinnedRooms: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 15,
      paddingVertical: 10,
      paddingLeft: 20,
      borderLeftWidth: 1,
      borderColor: "#D3DAE5",
    },
    chatHistorySidebarFooter: {
      width: "100%",
      flexDirection: "column",
      alignItems: "center",
      gap: verticalScale(15),
      backgroundColor: "white",
      padding: 20,
      borderBottomRightRadius: 16,
      borderTopWidth: 1,
      borderColor: "lightgrey",
      marginBottom: 10,
    },
    profileButton: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-start",
      gap: 15,
      alignItems: "center",
    },
    profilePic: {
      height: verticalScale(24),
      width: verticalScale(24),
      borderRadius: 7,
    },
    profileText: {
      fontSize: moderateScale(17),
      fontWeight: 600,
    },
    coinstar:{
      height:30,
      width:30,
      borderWidth:2,
      borderRadius:50,
      borderColor:appColors.navyBlueShade,
      justifyContent:"center",
      alignItems:"center"
    },
    upgradeBtn: {
      width: "100%",
      borderWidth: 1,
      borderColor: "#D3DAE5",
      borderRadius: 16,
      padding: 12,
      gap: 7,
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "flex-start",
    },
    madeinindia: {
      width: "100%",
      
    },
    chatInputMainWrapper: {
      width: "100%",
      paddingBottom: Platform.OS == "ios"? 15:20,
      zIndex: 2,
    },
    chatInputMain: {
      width: "100%",
      paddingHorizontal: 15,
      paddingBottom: 20,
      borderWidth: 1,
      borderColor: "#ABB8CC",
      borderRadius: Platform.OS == "ios"? 32:28,
      flexDirection: "column",
      alignItems: "center",
      gap: verticalScale(12),
      backgroundColor: "white",
    },
    filesContainerMain: {
      width: "94%",
      paddingVertical: 5,
      flexDirection: "row",
      paddingTop: 25,
      paddingRight: 20,
      paddingLeft: 7,
    },
    textInput: {
      width: "100%",
      minHeight: Platform.OS === 'ios' ? verticalScale(42) : verticalScale(37),
      paddingTop: Platform.OS === 'ios' ? 10 : 8,
      paddingBottom: Platform.OS === 'ios' ? 10 : 8,
      lineHeight: 20,
    },
    inputActionIconsMainWrapper: {
      height: verticalScale(32),
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    inputLeftActionIcons: {
      height: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: scale(8),
    },
    inputRightActionIcons: {
      height: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: scale(17),
    },
    toolsIconButton: {
      marginLeft: 10,
    },
    toolsIconButtonGuide: {
      marginLeft: 10,
      borderWidth: 1,
      padding: 6,
      borderColor: "#BFD6FE",
      borderRadius: 10,
      elevation: 10,
      backgroundColor: "white",
      shadowColor: "#426eb9ff",
    },
    parentContainer: {
      position: "relative", // important: makes children absolute to this view
      justifyContent: "center",
      alignItems: "center",
    },
    gettingResponseIndicator: {
      width: 35,
      height: 35,
      backgroundColor: "#081A35",
      borderRadius: 8,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    innerDotGettingresponse: {
      height: 10,
      width: 10,
      backgroundColor: "white",
      borderRadius: 1,
    },
  });
